import type { NormalizedEvent } from '../session/projection.js'
import type { HarnessRuntimeMetadata } from '../upstream/runtime.js'

export const TERMINAL_PLUGIN_API_VERSION = 1 as const

export type TerminalRuntimePhase = 'starting' | 'idle' | 'running' | 'closing' | 'failed'

export interface TerminalSessionSnapshot {
  sessionId: string
  turnCount: number
  generation: number
}

export interface TerminalCommandContext {
  runtime: HarnessRuntimeMetadata
  session: TerminalSessionSnapshot
  phase: TerminalRuntimePhase
  totalTurns: number
}

export type TerminalCommandOutcome =
  | { kind: 'message'; title?: string; text: string }
  | { kind: 'new-session' }
  | { kind: 'clear' }
  | { kind: 'exit' }
  | { kind: 'view'; viewId: string }
  | { kind: 'toggle-tools' }
  | { kind: 'fork-composition' }
  /**
   * Restart the owned runtime with a different selection. Protocol 0.0.1 has no
   * way to reconfigure a live runtime, so this is the only mechanism, and it
   * starts a new session — `warning` states that before anything happens.
   */
  | {
      kind: 'restart-runtime'
      selection: { provider?: string; model?: string; maxTokens?: number; runtimeConfig?: string }
      summary: string
    }

export interface TerminalCommandSpec {
  name: string
  aliases?: readonly string[]
  summary: string
  usage?: string
  execute(context: TerminalCommandContext, args: readonly string[]): TerminalCommandOutcome | Promise<TerminalCommandOutcome>
}

export type TranscriptBlockKind = 'user' | 'assistant' | 'tool' | 'agent' | 'error' | 'system' | 'debug'

export interface TranscriptBlock {
  id: string
  kind: TranscriptBlockKind
  title?: string
  /** Bounded local display copy; exact upstream execution content is unchanged. */
  text: string
  detail?: string
  /** Characters omitted from the middle of `text` by local retention. */
  textDroppedChars?: number
  /** Characters omitted from the middle of `detail` by local retention. */
  detailDroppedChars?: number
  state?: 'running' | 'success' | 'error' | 'finished'
  /**
   * Upstream event timestamps bounding the activity, in ms. The view derives
   * the elapsed span from these; it never reads a local clock, so an interval
   * shown to the user is always a span between two public upstream events.
   */
  startedAt?: number
  endedAt?: number
  foldable?: boolean
  sessionId?: string
  /** Local presentation grouping only; never an upstream causal id. */
  activityId?: string
}

export type TranscriptMutation =
  | { kind: 'append'; block: TranscriptBlock }
  | { kind: 'append-text'; id: string; text: string; fallback?: TranscriptBlock }
  | { kind: 'patch'; id: string; patch: Partial<Omit<TranscriptBlock, 'id'>> }
  | { kind: 'remove'; id: string }

/**
 * `activityId` is generated by dshc for terminal presentation only. It groups
 * events observed during one HarnessRuntime.run() interval and MUST NOT be
 * exposed as an upstream message id, turn id, or protocol causal identifier.
 * `rootSessionId` is the Harness session explicitly submitted to run(); it is
 * used only to distinguish that root from public descendant-session events.
 */
export interface TerminalRenderContext {
  debug: boolean
  activityId: string
  rootSessionId: string
}

export interface TerminalEventRendererSpec {
  id: string
  priority?: number
  match(event: NormalizedEvent): boolean
  render(event: NormalizedEvent, context: TerminalRenderContext): readonly TranscriptMutation[]
}

export interface TerminalAgentTopologyEntry {
  childSessionId: string
  parentSessionId: string
  provider?: string
  status: 'running' | 'finished'
}

export interface TerminalRetentionSummary {
  totalEventCount: number
  droppedEventCount: number
  droppedTranscriptBlockCount: number
  droppedTopologyEntryCount: number
}

export interface TerminalViewContext extends TerminalCommandContext {
  commands: readonly RegisteredCommandInfo[]
  renderers: readonly RegisteredRendererInfo[]
  plugins: readonly RegisteredPluginInfo[]
  /** Bounded normalized event tail. Exact totals/eviction live in `retention`. */
  events: readonly NormalizedEvent[]
  /** Optional to preserve API-v1 compatibility for external test/embedding code. */
  retention?: TerminalRetentionSummary
  /**
   * Composition dshc launched with, for display. Requested configuration, never
   * confirmation of what the runtime actually loaded.
   */
  composition?: {
    path: string
    source: 'shipped-default' | 'override'
    entries: readonly { id: string; settings: readonly string[] }[]
  }
  /** Tool activity entry the sidebar has selected, when one is focused. */
  selectedToolKey?: string
  /** Current selected-session topology projection, independent of trace eviction. */
  agentTopology?: readonly TerminalAgentTopologyEntry[]
}

export interface TerminalViewSpec {
  id: string
  title: string
  render(context: TerminalViewContext): string
}

export interface TerminalStatusSegmentSpec {
  id: string
  priority?: number
  render(context: TerminalCommandContext): string | undefined
}

export interface TerminalPluginSpec {
  id: string
  version: string
  apiVersion: typeof TERMINAL_PLUGIN_API_VERSION
  commands?: readonly TerminalCommandSpec[]
  eventRenderers?: readonly TerminalEventRendererSpec[]
  views?: readonly TerminalViewSpec[]
  statusSegments?: readonly TerminalStatusSegmentSpec[]
}

export interface RegisteredPluginInfo {
  id: string
  version: string
}

export interface RegisteredCommandInfo {
  name: string
  aliases: readonly string[]
  summary: string
  usage?: string
  pluginId: string
}

export interface RegisteredRendererInfo {
  id: string
  priority: number
  pluginId: string
}
