import type { NormalizedEvent } from '../session/projection.js'
import type { SessionUsage } from '../session/usage.js'
import type { HarnessRuntimeMetadata } from '../upstream/runtime.js'
import type { Preferences, WorkMode } from '../preferences.js'
import type { Locale } from '../i18n.js'
import type { ModelTelemetry } from '../session/model-telemetry.js'
import type { SessionTiming, CompactionStats } from '../session/session-clock.js'

export const TERMINAL_PLUGIN_API_VERSION = 1 as const

export type TerminalRuntimePhase = 'starting' | 'idle' | 'running' | 'closing' | 'failed'

export interface TerminalSessionSnapshot {
  sessionId: string
  turnCount: number
  generation: number
}

export interface TerminalCommandContext {
  sessionTiming?: SessionTiming
  compaction?: CompactionStats
  locale?: Locale
  preferences?: Partial<Preferences>
  runtime: HarnessRuntimeMetadata
  session: TerminalSessionSnapshot
  phase: TerminalRuntimePhase
  totalTurns: number
  /** Token accounting folded from upstream. Optional to keep API v1 compatible. */
  usage?: SessionUsage
  /** Optional local timing of observed model requests; API v1 remains compatible. */
  modelTelemetry?: ModelTelemetry
}

export type TerminalCommandOutcome =
  | { kind: 'sidebar'; page?: 'overview' | 'tools' }
  | { kind: 'profile-operation'; args: readonly string[] }
  | { kind: 'edit-input'; text: string }
  | { kind: 'external-editor' }
  | { kind: 'preferences'; patch: Partial<Preferences> }
  /**
   * Switch the work mode of the running runtime, keeping the session. When
   * that is impossible, `allowRestart` says whether the person already
   * confirmed the restart (and the lost conversation) that remains.
   */
  | { kind: 'switch-mode'; mode: WorkMode; allowRestart: boolean }
  | { kind: 'message'; title?: string; text: string }
  | { kind: 'new-session' }
  | { kind: 'clear' }
  | { kind: 'exit' }
  | { kind: 'view'; viewId: string }
  | { kind: 'toggle-tools' }
  | { kind: 'fork-composition' }
  | { kind: 'plugin-search'; query: string }
  | { kind: 'plugin-install'; spec: string; confirmed: boolean }
  /** First-party Ask History handoff; creates no history database or resumed session. */
  | { kind: 'submit-prompt'; prompt: string; displayText: string; sourceSummary: string; newSession: true }
  /**
   * Restart the owned runtime with a different selection. Protocol 0.0.1 has no
   * way to reconfigure a live runtime, so this is the only mechanism, and it
   * starts a new session — `warning` states that before anything happens.
   */
  | {
      kind: 'restart-runtime'
      selection: Partial<Preferences> & { provider?: string; model?: string; maxTokens?: number; runtimeConfig?: string }
      summary: string
    }

export interface TerminalCommandSpec {
  name: string
  aliases?: readonly string[]
  summary: string
  usage?: string
  execute(
    context: TerminalCommandContext,
    args: readonly string[],
    signal?: AbortSignal,
  ): TerminalCommandOutcome | Promise<TerminalCommandOutcome>
}

export type TranscriptBlockKind = 'user' | 'assistant' | 'tool' | 'agent' | 'error' | 'system' | 'debug'

export interface TranscriptBlock {
  id: string
  kind: TranscriptBlockKind
  title?: string
  /** Bounded local display copy; exact upstream execution content is unchanged. */
  text: string
  detail?: string
  /** Characters omitted from the middle of `text` by local retention. */
  textDroppedChars?: number
  /** Characters omitted from the middle of `detail` by local retention. */
  detailDroppedChars?: number
  state?: 'running' | 'success' | 'error' | 'finished'
  /**
   * Upstream event timestamps bounding the activity, in ms. The view derives
   * the elapsed span from these; it never reads a local clock, so an interval
   * shown to the user is always a span between two public upstream events.
   */
  startedAt?: number
  endedAt?: number
  foldable?: boolean
  sessionId?: string
  /** Local presentation grouping only; never an upstream causal id. */
  activityId?: string
}

export type TranscriptMutation =
  | { kind: 'append'; block: TranscriptBlock }
  | { kind: 'append-text'; id: string; text: string; fallback?: TranscriptBlock }
  | { kind: 'patch'; id: string; patch: Partial<Omit<TranscriptBlock, 'id'>> }
  | { kind: 'remove'; id: string }

/**
 * `activityId` is generated by dshc for terminal presentation only. It groups
 * events observed during one HarnessRuntime.run() interval and MUST NOT be
 * exposed as an upstream message id, turn id, or protocol causal identifier.
 * `rootSessionId` is the Harness session explicitly submitted to run(); it is
 * used only to distinguish that root from public descendant-session events.
 */
export interface TerminalRenderContext {
  debug: boolean
  activityId: string
  rootSessionId: string
  /** Local presentation only: where paths resolve for risk hints. Optional for API-v1 callers. */
  workspace?: string
  /** Local presentation only: the language for labels. Optional for API-v1 callers. */
  locale?: Locale
}

export interface TerminalEventRendererSpec {
  id: string
  eventKinds?: readonly NormalizedEvent['kind'][]
  priority?: number
  match(event: NormalizedEvent): boolean
  render(event: NormalizedEvent, context: TerminalRenderContext): readonly TranscriptMutation[]
}

export interface TerminalAgentTopologyEntry {
  childSessionId: string
  parentSessionId: string
  provider?: string
  status: 'running' | 'finished'
}

export interface TerminalRetentionSummary {
  totalEventCount: number
  droppedEventCount: number
  droppedTranscriptBlockCount: number
  droppedTopologyEntryCount: number
}

export interface TerminalViewContext extends TerminalCommandContext {
  commands: readonly RegisteredCommandInfo[]
  renderers: readonly RegisteredRendererInfo[]
  plugins: readonly RegisteredPluginInfo[]
  /** Bounded normalized event tail. Exact totals/eviction live in `retention`. */
  events: readonly NormalizedEvent[]
  /** Optional to preserve API-v1 compatibility for external test/embedding code. */
  retention?: TerminalRetentionSummary
  /**
   * Composition dshc launched with, for display. Requested configuration, never
   * confirmation of what the runtime actually loaded.
   */
  composition?: {
    path: string
    source: 'shipped-default' | 'workspace' | 'override'
    entries: readonly { id: string; settings: readonly string[] }[]
    base: {
      path: string
      source: 'shipped-default' | 'workspace' | 'override'
      entries: readonly { id: string; settings: readonly string[] }[]
    }
    patch?: { path: string; patchCount: number }
    patches?: readonly { path: string; patchCount: number; kind?: 'developer' | 'workspace' }[]
    effective: { entries: readonly { id: string; settings: readonly string[] }[] }
  }
  /** Tool activity entry the sidebar has selected, when one is focused. */
  selectedToolKey?: string
  /** Current selected-session topology projection, independent of trace eviction. */
  agentTopology?: readonly TerminalAgentTopologyEntry[]
}

export interface TerminalViewSpec {
  id: string
  eventKinds?: readonly NormalizedEvent['kind'][]
  title: string
  render(context: TerminalViewContext): string
}

export interface TerminalStatusSegmentSpec {
  id: string
  priority?: number
  render(context: TerminalCommandContext): string | undefined
}

export interface TerminalPluginSpec {
  id: string
  locales?: Partial<Record<Locale, Readonly<Record<string, string>>>>
  version: string
  apiVersion: typeof TERMINAL_PLUGIN_API_VERSION
  commands?: readonly TerminalCommandSpec[]
  eventRenderers?: readonly TerminalEventRendererSpec[]
  views?: readonly TerminalViewSpec[]
  statusSegments?: readonly TerminalStatusSegmentSpec[]
}

export interface RegisteredPluginInfo {
  id: string
  version: string
}

export interface RegisteredCommandInfo {
  name: string
  aliases: readonly string[]
  summary: string
  usage?: string
  pluginId: string
}

export interface RegisteredRendererInfo {
  id: string
  priority: number
  pluginId: string
}
